config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :agences

  resources :principal_groupes

  resources :sous_groupes

  resources :travailleurs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/principal_groupe.rb
class PrincipalGroupe < ActiveRecord::Base
  has_many :users
  has_many :sous_groupes
end

app/controllers/principal_groupes_controller.rb
class PrincipalGroupesController < ApplicationController
  before_action :set_principal_groupe, only: [:show, :edit, :update, :destroy]

  # GET /principal_groupes
  # GET /principal_groupes.json
  def index
    @principal_groupes = PrincipalGroupe.all
  end

  # GET /principal_groupes/1
  # GET /principal_groupes/1.json
  def show
  end

  # GET /principal_groupes/new
  def new
    @principal_groupe = PrincipalGroupe.new
  end

  # GET /principal_groupes/1/edit
  def edit
  end

  # POST /principal_groupes
  # POST /principal_groupes.json
  def create
    @principal_groupe = PrincipalGroupe.new(principal_groupe_params)

    respond_to do |format|
      if @principal_groupe.save
        format.html { redirect_to @principal_groupe, notice: 'Principal groupe was successfully created.' }
        format.json { render :show, status: :created, location: @principal_groupe }
      else
        format.html { render :new }
        format.json { render json: @principal_groupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /principal_groupes/1
  # PATCH/PUT /principal_groupes/1.json
  def update
    respond_to do |format|
      if @principal_groupe.update(principal_groupe_params)
        format.html { redirect_to @principal_groupe, notice: 'Principal groupe was successfully updated.' }
        format.json { render :show, status: :ok, location: @principal_groupe }
      else
        format.html { render :edit }
        format.json { render json: @principal_groupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principal_groupes/1
  # DELETE /principal_groupes/1.json
  def destroy
    @principal_groupe.destroy
    respond_to do |format|
      format.html { redirect_to principal_groupes_url, notice: 'Principal groupe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_principal_groupe
      @principal_groupe = PrincipalGroupe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def principal_groupe_params
      params.require(:principal_groupe).permit(:name)
    end
end

app/helpers/principal_groupes_helper.rb
module PrincipalGroupesHelper
end

app/views/principal_groupes/_form.html.erb
<%= form_for @principal_groupe, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  principal_groupes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/principal_groupes/edit.html.erb
<%- model_class = PrincipalGroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => PrincipalGroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/principal_groupes/index.html.erb
<%- model_class = PrincipalGroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => PrincipalGroupe %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @principal_groupes.each do |principal_groupe| %>
      <tr>
        <td><%= principal_groupe.id %></td>
        <td><%= principal_groupe.name %></td>
        <td><%=l principal_groupe.created_at, format: :long %></td>
        <td>
          <%= link_to principal_groupe_path(principal_groupe), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to principal_groupe_path(principal_groupe), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_principal_groupe_path,
            :class => 'btn btn-primary' %>

app/views/principal_groupes/new.html.erb
<%- model_class = PrincipalGroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => PrincipalGroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/principal_groupes/show.html.erb
<%- model_class = PrincipalGroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => PrincipalGroupe %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @principal_groupe.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              principal_groupes_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_principal_groupe_path(@principal_groupe), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              principal_groupe_path(@principal_groupe),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>