config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :agences

  resources :principal_groupes

  resources :sous_groupes

  resources :travailleurs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/sous_groupe.rb
class SousGroupe < ActiveRecord::Base
  belongs_to :principal_groupe
  has_many :users
end

app/controllers/sous_groupes_controller.rb
class SousGroupesController < ApplicationController
  before_action :set_sous_groupe, only: [:show, :edit, :update, :destroy]

  # GET /sous_groupes
  # GET /sous_groupes.json
  def index
    @sous_groupes = SousGroupe.all
  end

  # GET /sous_groupes/1
  # GET /sous_groupes/1.json
  def show
  end

  # GET /sous_groupes/new
  def new
    @sous_groupe = SousGroupe.new
  end

  # GET /sous_groupes/1/edit
  def edit
  end

  # POST /sous_groupes
  # POST /sous_groupes.json
  def create
    @sous_groupe = SousGroupe.new(sous_groupe_params)

    respond_to do |format|
      if @sous_groupe.save
        format.html { redirect_to @sous_groupe, notice: 'Sous groupe was successfully created.' }
        format.json { render :show, status: :created, location: @sous_groupe }
      else
        format.html { render :new }
        format.json { render json: @sous_groupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sous_groupes/1
  # PATCH/PUT /sous_groupes/1.json
  def update
    respond_to do |format|
      if @sous_groupe.update(sous_groupe_params)
        format.html { redirect_to @sous_groupe, notice: 'Sous groupe was successfully updated.' }
        format.json { render :show, status: :ok, location: @sous_groupe }
      else
        format.html { render :edit }
        format.json { render json: @sous_groupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sous_groupes/1
  # DELETE /sous_groupes/1.json
  def destroy
    @sous_groupe.destroy
    respond_to do |format|
      format.html { redirect_to sous_groupes_url, notice: 'Sous groupe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sous_groupe
      @sous_groupe = SousGroupe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sous_groupe_params
      params.require(:sous_groupe).permit(:nom, :principal_groupe_id)
    end
end

app/helpers/sous_groupes_helper.rb
module SousGroupesHelper
end

app/views/sous_groupes/_form.html.erb
<%= form_for @sous_groupe, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :nom, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :nom, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  sous_groupes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/sous_groupes/edit.html.erb
<%- model_class = SousGroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => SousGroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sous_groupes/index.html.erb
<%- model_class = SousGroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => SousGroupe %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:nom) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sous_groupes.each do |sous_groupe| %>
      <tr>
        <td><%= sous_groupe.id %></td>
        <td><%= sous_groupe.nom %></td>
        <td><%=l sous_groupe.created_at, format: :long %></td>
        <td>
          <%= link_to sous_groupe_path(sous_groupe), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to sous_groupe_path(sous_groupe), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sous_groupe_path,
            :class => 'btn btn-primary' %>

app/views/sous_groupes/new.html.erb
<%- model_class = SousGroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => SousGroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sous_groupes/show.html.erb
<%- model_class = SousGroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => SousGroupe %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nom) %></dt>
      <dd><pre class="prettyprint"><%= @sous_groupe.nom %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sous_groupes_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sous_groupe_path(@sous_groupe), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sous_groupe_path(@sous_groupe),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>