config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :agences

  resources :principal_groupes

  resources :sous_groupes

  resources :travailleurs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/travailleur.rb
class Travailleur < ActiveRecord::Base
  belongs_to :principal_groupe
  belongs_to :sous_groupe
  belongs_to :agence
  has_one :user
end

app/controllers/travailleurs_controller.rb
class TravailleursController < ApplicationController
  before_action :set_travailleur, only: [:show, :edit, :update, :destroy]

  # GET /travailleurs
  # GET /travailleurs.json
  def index
    @travailleurs = Travailleur.all
  end

  # GET /travailleurs/1
  # GET /travailleurs/1.json
  def show
  end

  # GET /travailleurs/new
  def new
    @travailleur = Travailleur.new
  end

  # GET /travailleurs/1/edit
  def edit
  end

  # POST /travailleurs
  # POST /travailleurs.json
  def create
    @travailleur = Travailleur.new(travailleur_params)

    respond_to do |format|
      if @travailleur.save
        format.html { redirect_to @travailleur, notice: 'Travailleur was successfully created.' }
        format.json { render :show, status: :created, location: @travailleur }
      else
        format.html { render :new }
        format.json { render json: @travailleur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travailleurs/1
  # PATCH/PUT /travailleurs/1.json
  def update
    respond_to do |format|
      if @travailleur.update(travailleur_params)
        format.html { redirect_to @travailleur, notice: 'Travailleur was successfully updated.' }
        format.json { render :show, status: :ok, location: @travailleur }
      else
        format.html { render :edit }
        format.json { render json: @travailleur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travailleurs/1
  # DELETE /travailleurs/1.json
  def destroy
    @travailleur.destroy
    respond_to do |format|
      format.html { redirect_to travailleurs_url, notice: 'Travailleur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travailleur
      @travailleur = Travailleur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travailleur_params
      params.require(:travailleur).permit(:nom, :principal_groupe_id, :sous_groupe_id, :agence_id)
    end
end

app/helpers/travailleurs_helper.rb
module TravailleursHelper
end

app/views/travailleurs/_form.html.erb
<%= form_for @travailleur, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :nom, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nom, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  travailleurs_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/travailleurs/edit.html.erb
<%- model_class = Travailleur -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Travailleur %></h1>
</div>
<%= render :partial => 'form' %>

app/views/travailleurs/index.html.erb
<%- model_class = Travailleur -%>
<div class="page-header">
  <h1><%=t '.title', :default => Travailleur %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:nom) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @travailleurs.each do |travailleur| %>
      <tr>
        <td><%= travailleur.id %></td>
        <td><%= travailleur.nom %></td>
        <td><%=l travailleur.created_at, format: :long %></td>
        <td>
          <%= link_to travailleur_path(travailleur), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to travailleur_path(travailleur), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_travailleur_path,
            :class => 'btn btn-primary' %>

app/views/travailleurs/new.html.erb
<%- model_class = Travailleur -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Travailleur %></h1>
</div>
<%= render :partial => 'form' %>

app/views/travailleurs/show.html.erb
<%- model_class = Travailleur -%>
<div class="page-header">
  <h1><%=t '.title', :default => Travailleur %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nom) %></dt>
      <dd><pre class="prettyprint"><%= @travailleur.nom %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              travailleurs_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_travailleur_path(@travailleur), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              travailleur_path(@travailleur),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>